#!/usr/bin/env sh

# Fetch the directory of this script.
base_dir="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)/../Resources"

# Find the dir containing the app script
app_dir="$base_dir/rel/app/bin"

# Not too important. Used for local HTTPS only
export SECRET_KEY_BASE="hZ79GD4tI0QeWsEN3vmB35cmx2vURccImu16hsW7uE99uaB6mN8dRf3YgczokiJt"

# Start the app
$app_dir/app start
